apiVersion: v1
kind: Pod
metadata:
  name: health-check-service
spec:
  containers:
    - name: health-check-service
      image: health-check-service:0.0.4-snapshot
      imagePullPolicy: Never
      args: [
        "--port", "8080",
        "--gtfs-lookup.host", "gtfs-lookup-service",
        "--gtfs-lookup.port", "8080",
        "--organization.host", "organization-service",
        "--organization.port", "8080"
      ]
  restartPolicy: Always